language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Formatting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
